//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LounaTravelDbContext : DbContext
    {
        public LounaTravelDbContext()
            : base("name=LounaTravelDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Booking> tbl_Booking { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Convenient> tbl_Convenient { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_FeedBack> tbl_FeedBack { get; set; }
        public virtual DbSet<tbl_Flight> tbl_Flight { get; set; }
        public virtual DbSet<tbl_Image> tbl_Image { get; set; }
        public virtual DbSet<tbl_ImageHotel> tbl_ImageHotel { get; set; }
        public virtual DbSet<tbl_Office> tbl_Office { get; set; }
        public virtual DbSet<tbl_Region> tbl_Region { get; set; }
        public virtual DbSet<tbl_TourDetail> tbl_TourDetail { get; set; }
        public virtual DbSet<tbl_TourGuide> tbl_TourGuide { get; set; }
        public virtual DbSet<tbl_Travel_Type> tbl_Travel_Type { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Passenger> tbl_Passenger { get; set; }
        public virtual DbSet<tbl_Hotel> tbl_Hotel { get; set; }
        public virtual DbSet<tbl_Metadata> tbl_Metadata { get; set; }
        public virtual DbSet<tbl_Tour> tbl_Tour { get; set; }
    
        public virtual ObjectResult<db_Get_All_Hotel_Result> db_Get_All_Hotel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_All_Hotel_Result>("db_Get_All_Hotel");
        }
    
        public virtual ObjectResult<db_Get_City_By_CityID_From_tblHotel_Result> db_Get_City_By_CityID_From_tblHotel(Nullable<int> cityID)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_City_By_CityID_From_tblHotel_Result>("db_Get_City_By_CityID_From_tblHotel", cityIDParameter);
        }
    
        public virtual ObjectResult<db_Get_Image_By_HotelID_Result> db_Get_Image_By_HotelID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_Image_By_HotelID_Result>("db_Get_Image_By_HotelID", iDParameter);
        }
    
        public virtual ObjectResult<db_Get_List_ComboBox_ToPlace_Result> db_Get_List_ComboBox_ToPlace()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_List_ComboBox_ToPlace_Result>("db_Get_List_ComboBox_ToPlace");
        }
    
        public virtual ObjectResult<db_Get_List_Convenient_Result> db_Get_List_Convenient(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_List_Convenient_Result>("db_Get_List_Convenient", iDParameter);
        }
    
        public virtual ObjectResult<db_Get_List_Hotel_Hot_Details_Result> db_Get_List_Hotel_Hot_Details(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_List_Hotel_Hot_Details_Result>("db_Get_List_Hotel_Hot_Details", iDParameter);
        }
    
        public virtual ObjectResult<db_Get_List_Search_Hotel_Result> db_Get_List_Search_Hotel(Nullable<System.DateTime> checkIn, Nullable<System.DateTime> checkOut, Nullable<int> cityID)
        {
            var checkInParameter = checkIn.HasValue ?
                new ObjectParameter("CheckIn", checkIn) :
                new ObjectParameter("CheckIn", typeof(System.DateTime));
    
            var checkOutParameter = checkOut.HasValue ?
                new ObjectParameter("CheckOut", checkOut) :
                new ObjectParameter("CheckOut", typeof(System.DateTime));
    
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_List_Search_Hotel_Result>("db_Get_List_Search_Hotel", checkInParameter, checkOutParameter, cityIDParameter);
        }
    
        public virtual ObjectResult<db_Get_List_Search_Tour_Result> db_Get_List_Search_Tour(Nullable<int> fromPlace, Nullable<int> toPlace, Nullable<System.DateTime> timeBegin, Nullable<int> seatsRemaining)
        {
            var fromPlaceParameter = fromPlace.HasValue ?
                new ObjectParameter("fromPlace", fromPlace) :
                new ObjectParameter("fromPlace", typeof(int));
    
            var toPlaceParameter = toPlace.HasValue ?
                new ObjectParameter("toPlace", toPlace) :
                new ObjectParameter("toPlace", typeof(int));
    
            var timeBeginParameter = timeBegin.HasValue ?
                new ObjectParameter("timeBegin", timeBegin) :
                new ObjectParameter("timeBegin", typeof(System.DateTime));
    
            var seatsRemainingParameter = seatsRemaining.HasValue ?
                new ObjectParameter("seatsRemaining", seatsRemaining) :
                new ObjectParameter("seatsRemaining", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Get_List_Search_Tour_Result>("db_Get_List_Search_Tour", fromPlaceParameter, toPlaceParameter, timeBeginParameter, seatsRemainingParameter);
        }
    
        public virtual ObjectResult<get_All_Tour_Current_Result> get_All_Tour_Current()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_All_Tour_Current_Result>("get_All_Tour_Current");
        }
    
        public virtual ObjectResult<get_List_Tour_Hot_Result> get_List_Tour_Hot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_List_Tour_Hot_Result>("get_List_Tour_Hot");
        }
    
        public virtual ObjectResult<getAgeFrom0To18_Result> getAgeFrom0To18()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgeFrom0To18_Result>("getAgeFrom0To18");
        }
    
        public virtual ObjectResult<getAgeFrom18To40_Result> getAgeFrom18To40()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgeFrom18To40_Result>("getAgeFrom18To40");
        }
    
        public virtual ObjectResult<getAgeFrom40To60_Result> getAgeFrom40To60()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgeFrom40To60_Result>("getAgeFrom40To60");
        }
    
        public virtual ObjectResult<getAgeFrom60To100_Result> getAgeFrom60To100()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgeFrom60To100_Result>("getAgeFrom60To100");
        }
    
        public virtual ObjectResult<Nullable<int>> getChildrenOfUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getChildrenOfUser");
        }
    
        public virtual ObjectResult<Nullable<int>> getJuvenileOfUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getJuvenileOfUser");
        }
    
        public virtual ObjectResult<getListHotel_Result> getListHotel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListHotel_Result>("getListHotel");
        }
    
        public virtual ObjectResult<Nullable<int>> getYearOfUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getYearOfUser");
        }
    
        public virtual ObjectResult<Load_Image_Tour_Search_Result> Load_Image_Tour_Search(string tourID)
        {
            var tourIDParameter = tourID != null ?
                new ObjectParameter("TourID", tourID) :
                new ObjectParameter("TourID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Image_Tour_Search_Result>("Load_Image_Tour_Search", tourIDParameter);
        }
    
        public virtual ObjectResult<load_img_hotel_by_HotelID_Result> load_img_hotel_by_HotelID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<load_img_hotel_by_HotelID_Result>("load_img_hotel_by_HotelID", iDParameter);
        }
    
        public virtual ObjectResult<loadImgByTourId_Result> loadImgByTourId(string tourID)
        {
            var tourIDParameter = tourID != null ?
                new ObjectParameter("TourID", tourID) :
                new ObjectParameter("TourID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loadImgByTourId_Result>("loadImgByTourId", tourIDParameter);
        }
    
        public virtual ObjectResult<sp_get_City_ByRegionID_Result> sp_get_City_ByRegionID(Nullable<int> regionID)
        {
            var regionIDParameter = regionID.HasValue ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_City_ByRegionID_Result>("sp_get_City_ByRegionID", regionIDParameter);
        }
    
        public virtual ObjectResult<sp_get_Metadata_Result> sp_get_Metadata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_Metadata_Result>("sp_get_Metadata");
        }
    
        public virtual ObjectResult<sp_get_Office_ByCityID_Result> sp_get_Office_ByCityID(Nullable<int> cityID)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_Office_ByCityID_Result>("sp_get_Office_ByCityID", cityIDParameter);
        }
    
        public virtual ObjectResult<sp_get_Office_ByID_Result> sp_get_Office_ByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_Office_ByID_Result>("sp_get_Office_ByID", iDParameter);
        }
    
        public virtual ObjectResult<spGet_All_Main_Office_In_Center_VietNam_Result> spGet_All_Main_Office_In_Center_VietNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Main_Office_In_Center_VietNam_Result>("spGet_All_Main_Office_In_Center_VietNam");
        }
    
        public virtual ObjectResult<spGet_All_Main_Office_In_North_VietNam_Result> spGet_All_Main_Office_In_North_VietNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Main_Office_In_North_VietNam_Result>("spGet_All_Main_Office_In_North_VietNam");
        }
    
        public virtual ObjectResult<spGet_All_Main_Office_In_South_VietNam_Result> spGet_All_Main_Office_In_South_VietNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Main_Office_In_South_VietNam_Result>("spGet_All_Main_Office_In_South_VietNam");
        }
    
        public virtual ObjectResult<spGet_All_Main_Office_In_VietNam_Result> spGet_All_Main_Office_In_VietNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Main_Office_In_VietNam_Result>("spGet_All_Main_Office_In_VietNam");
        }
    
        public virtual ObjectResult<spGet_All_Office_In_VietNam_Result> spGet_All_Office_In_VietNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Office_In_VietNam_Result>("spGet_All_Office_In_VietNam");
        }
    
        public virtual ObjectResult<spGet_FeedBack_By_TourID_Result> spGet_FeedBack_By_TourID(string tourID)
        {
            var tourIDParameter = tourID != null ?
                new ObjectParameter("tourID", tourID) :
                new ObjectParameter("tourID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_FeedBack_By_TourID_Result>("spGet_FeedBack_By_TourID", tourIDParameter);
        }
    
        public virtual ObjectResult<spGet_Hotel_by_Tour_ID_Result> spGet_Hotel_by_Tour_ID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_Hotel_by_Tour_ID_Result>("spGet_Hotel_by_Tour_ID", iDParameter);
        }
    
        public virtual ObjectResult<spGet_Reply_By_FeedBackID_Result> spGet_Reply_By_FeedBackID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_Reply_By_FeedBackID_Result>("spGet_Reply_By_FeedBackID", iDParameter);
        }
    
        public virtual ObjectResult<spGet_Tour_byID_Result> spGet_Tour_byID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_Tour_byID_Result>("spGet_Tour_byID", iDParameter);
        }
    
        public virtual int db_Update_User(string username, string firstName, string lastName, string email, string phoneNumber)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("db_Update_User", usernameParameter, firstNameParameter, lastNameParameter, emailParameter, phoneNumberParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_Get_City_Have_Office_Result> sp_Get_City_Have_Office()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_City_Have_Office_Result>("sp_Get_City_Have_Office");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
