//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Passenger
    {
        public int PassengerID { get; set; }
        public string Fullname { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Gender { get; set; }
        public string Phone { get; set; }
        public bool isDelete { get; set; }
        public int BookingID { get; set; }
        public string Type { get; set; }
    
        public virtual tbl_Booking tbl_Booking { get; set; }
    }
}
