//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Metadata
    {
        public int ID { get; set; }
        public string WebName { get; set; }
        public int Count { get; set; }
        public string Copyright { get; set; }
        public bool isDelete { get; set; }
    }
}
