//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Tour()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
            this.tbl_FeedBack = new HashSet<tbl_FeedBack>();
            this.tbl_Image = new HashSet<tbl_Image>();
            this.tbl_TourDetail = new HashSet<tbl_TourDetail>();
            this.tbl_Hotel = new HashSet<tbl_Hotel>();
        }
    
        public string ID { get; set; }
        public System.DateTime TimeBegin { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public double PriceForKid { get; set; }
        public double PriceForBaby { get; set; }
        public double PriceForAdult { get; set; }
        public string Vehicle { get; set; }
        public int TourGuideID { get; set; }
        public int SeatsRemaining { get; set; }
        public int TotalSeats { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public int TravelTypeID { get; set; }
        public int fromPlace { get; set; }
        public bool isDelete { get; set; }
        public Nullable<bool> isHot { get; set; }
        public Nullable<int> rating { get; set; }
        public string FlightID { get; set; }
        public string GroupUpPlace { get; set; }
        public System.DateTime GroupUpTime { get; set; }
        public string MeetingPlace { get; set; }
        public Nullable<System.DateTime> MeetingTime { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
        public virtual tbl_City tbl_FromPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FeedBack> tbl_FeedBack { get; set; }
        public virtual tbl_Flight tbl_Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Image> tbl_Image { get; set; }
        public virtual tbl_Travel_Type tbl_Travel_Type { get; set; }
        public virtual tbl_TourGuide tbl_TourGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TourDetail> tbl_TourDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hotel> tbl_Hotel { get; set; }
    }
}
