//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TourDetail
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string DateContent { get; set; }
        public bool isDelete { get; set; }
        public string TourID { get; set; }
        public int CityID { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Tour tbl_Tour { get; set; }
    }
}
