//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LounaTravel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImageHotel
    {
        public int ID { get; set; }
        public int HotelID { get; set; }
        public string Path { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tbl_Hotel tbl_Hotel { get; set; }
    }
}
